// <auto-generated />
namespace VideoTutor.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edit_design : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_design));
        
        string IMigrationMetadata.Id
        {
            get { return "201607200343157_edit_design"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
